version: '3.3'

# servicios a ejecutar
services:

# MySQL con nombre `bikemap-db`
  db:
    image: mysql:8.0.31
    container_name: bikemap-db
    environment:
    - MYSQL_DATABASE=bikemap
    - MYSQL_USER=bikemap
    - MYSQL_PASSWORD=secret
    - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    expose:
      - '3306'