#name -- Nombre que aparece en el listado de actions
name: Compilar y probar con Maven

#on -- eventos que disparan (inician) el flujo de tareas
on:
  workflow_dispatch:

#jobs -- tareas (conjuntos de pasos)
jobs:
  #nombre de la tarea
  compilar-probar:
    runs-on: ubuntu-latest

    steps:
    - name: Descarga el proyecto
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Ejecutar mySQL
      run: docker compose up -d
      
    - name: Build with Maven
      run: cd bikemap/; mvn -B package -DskipTests 

    - name: Prueba
      run: cd bikemap/; mvn test
